// Auto-generated by scripts/sync-version.mjs — do not edit
const CACHE = 'elecdog-v0.25.1';
const PRECACHE = [
  "./",
  "./index.html",
  "./style.css?v=0.25.1",
  "./src/main.js?v=0.25.1",
  "./manifest.webmanifest",
  "./icons/icon.svg",
  "./src/being/being.js?v=0.25.1",
  "./src/birth/ritual.js?v=0.25.1",
  "./src/core/dna.js?v=0.25.1",
  "./src/core/hash.js?v=0.25.1",
  "./src/core/id.js?v=0.25.1",
  "./src/kernel/engine.js?v=0.25.1",
  "./src/pwa.js?v=0.25.1",
  "./src/recorder/logger.js?v=0.25.1",
  "./src/ui/observer.js?v=0.25.1",
  "./src/ui/stats.js?v=0.25.1",
  "./src/version.js?v=0.25.1",
  "./src/world/biotic.js?v=0.25.1",
  "./src/world/catastrophe.js?v=0.25.1",
  "./src/world/cell.js?v=0.25.1",
  "./src/world/composition.js?v=0.25.1",
  "./src/world/lineage.js?v=0.25.1",
  "./src/world/nodes.js?v=0.25.1",
  "./src/world/social.js?v=0.25.1",
  "./src/world/substrate.js?v=0.25.1",
  "./src/world/viability.js?v=0.25.1",
  "./src/world/world.js?v=0.25.1"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((res) => {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', clone));
          return res;
        })
        .catch(() => caches.match('./index.html'))
    );
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((res) => {
        if (res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put(event.request, clone));
        }
        return res;
      })
      .catch(() => caches.match(event.request))
  );
});
