#!/usr/bin/env node
/**
 * 从 package.json 同步版本号到各处（唯一手动维护处：package.json version）
 * 生成：src/version.js、manifest.webmanifest、index.html 缓存参数
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = pkg.version;

if (!version) {
  console.error('package.json 缺少 version 字段');
  process.exit(1);
}

writeFileSync(
  join(root, 'src/version.js'),
  `// Auto-generated by scripts/sync-version.mjs — do not edit
export const VERSION = '${version}';

export function getAppVersion() {
  return document.querySelector('meta[name="elecdog-version"]')?.content?.trim() || VERSION;
}
`
);

const manifest = {
  name: 'ElecDog · 电子狗世界实况',
  short_name: 'ElecDog',
  description: '电子狗世界观察台 — 环境 / 种群 / 个体辞典统计',
  version,
  start_url: './',
  scope: './',
  display: 'standalone',
  background_color: '#080a0e',
  theme_color: '#0d1018',
  lang: 'zh-CN',
  icons: [
    {
      src: './icons/icon.svg',
      sizes: 'any',
      type: 'image/svg+xml',
      purpose: 'any',
    },
  ],
};

writeFileSync(join(root, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2) + '\n');

let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace(/href="style\.css(\?v=[^"]*)?"/, `href="style.css?v=${version}"`);
html = html.replace(/import\('\.\/src\/main\.js(\?v=[^"]*)?'\)/, `import('./src/main.js?v=${version}')`);
if (html.includes('src="src/main.js')) {
  html = html.replace(/src="src\/main\.js(\?v=[^"]*)?"/, `src="src/main.js?v=${version}"`);
}
if (html.includes('name="elecdog-version"')) {
  html = html.replace(
    /(<meta[^>]*name="elecdog-version"[^>]*content=")[^"]*(")/,
    (_, a, b) => `${a}${version}${b}`
  );
  html = html.replace(
    /(<meta[^>]*content=")[^"]*("[^>]*name="elecdog-version")/,
    (_, a, b) => `${a}${version}${b}`
  );
}
writeFileSync(join(root, 'index.html'), html);

console.log(`版本已同步: ${version}`);
