#!/usr/bin/env node
/**
 * 从 package.json 同步版本号到各处（唯一手动维护处：package.json version）
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = pkg.version;

if (!version) {
  console.error('package.json 缺少 version 字段');
  process.exit(1);
}

writeFileSync(
  join(root, 'src/version.js'),
  `// Auto-generated by scripts/sync-version.mjs — do not edit\nexport const VERSION = '${version}';\n`
);

let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace(/href="style\.css(\?v=[^"]*)?"/, `href="style.css?v=${version}"`);
html = html.replace(/src="src\/main\.js(\?v=[^"]*)?"/, `src="src/main.js?v=${version}"`);
if (html.includes('name="elecdog-version"')) {
  html = html.replace(/content="[^"]*" name="elecdog-version"/, `content="${version}" name="elecdog-version"`);
} else {
  html = html.replace(
    '<meta name="viewport"',
    `<meta name="elecdog-version" content="${version}" />\n    <meta name="viewport"`
  );
}
writeFileSync(join(root, 'index.html'), html);

console.log(`版本已同步: ${version}`);
