#!/usr/bin/env node
/**
 * 从 package.json 同步版本号到各处（唯一手动维护处：package.json version）
 * 生成：src/version.js、sw.js、manifest.webmanifest、index.html 缓存参数
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = pkg.version;

if (!version) {
  console.error('package.json 缺少 version 字段');
  process.exit(1);
}

function walkJs(dir, prefix = '') {
  const files = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      files.push(...walkJs(full, join(prefix, name)));
    } else if (name.endsWith('.js')) {
      const rel = `./src/${join(prefix, name).replace(/\\/g, '/')}`;
      files.push(`${rel}?v=${version}`);
    }
  }
  return files;
}

const srcFiles = walkJs(join(root, 'src'));
const precache = [
  './',
  './index.html',
  `./style.css?v=${version}`,
  `./src/main.js?v=${version}`,
  './manifest.webmanifest',
  './icons/icon.svg',
  ...srcFiles.filter((f) => !f.startsWith('./src/main.js')),
];

writeFileSync(
  join(root, 'src/version.js'),
  `// Auto-generated by scripts/sync-version.mjs — do not edit\nexport const VERSION = '${version}';\n`
);

const sw = `// Auto-generated by scripts/sync-version.mjs — do not edit
const CACHE = 'elecdog-v${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((res) => {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', clone));
          return res;
        })
        .catch(() => caches.match('./index.html'))
    );
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((res) => {
        if (res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put(event.request, clone));
        }
        return res;
      })
      .catch(() => caches.match(event.request))
  );
});
`;

writeFileSync(join(root, 'sw.js'), sw);

const manifest = {
  name: 'ElecDog · 电子狗世界实况',
  short_name: 'ElecDog',
  description: '电子狗世界观察台 — 环境 / 种群 / 个体辞典统计',
  version,
  start_url: './',
  scope: './',
  display: 'standalone',
  background_color: '#080a0e',
  theme_color: '#0d1018',
  lang: 'zh-CN',
  icons: [
    {
      src: './icons/icon.svg',
      sizes: 'any',
      type: 'image/svg+xml',
      purpose: 'any',
    },
  ],
};

writeFileSync(join(root, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2) + '\n');

let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace(/href="style\.css(\?v=[^"]*)?"/, `href="style.css?v=${version}"`);
html = html.replace(/src="src\/main\.js(\?v=[^"]*)?"/, `src="src/main.js?v=${version}"`);
if (html.includes('name="elecdog-version"')) {
  html = html.replace(
    /(<meta[^>]*name="elecdog-version"[^>]*content=")[^"]*(")/,
    (_, a, b) => `${a}${version}${b}`
  );
  html = html.replace(
    /(<meta[^>]*content=")[^"]*("[^>]*name="elecdog-version")/,
    (_, a, b) => `${a}${version}${b}`
  );
} else {
  html = html.replace(
    '<meta name="viewport"',
    `<meta name="elecdog-version" content="${version}" />\n    <meta name="viewport"`
  );
}
if (!html.includes('rel="manifest"')) {
  html = html.replace(
    '<title>',
    `<link rel="manifest" href="manifest.webmanifest" />\n    <meta name="theme-color" content="#0d1018" />\n    <meta name="apple-mobile-web-app-capable" content="yes" />\n    <link rel="icon" href="icons/icon.svg" type="image/svg+xml" />\n    <title>`
  );
}
writeFileSync(join(root, 'index.html'), html);

console.log(`版本已同步: ${version}（含 PWA manifest + service worker）`);
