// Auto-generated by scripts/sync-version.mjs — do not edit
export const VERSION = '0.25.4';

export function getAppVersion() {
  return document.querySelector('meta[name="elecdog-version"]')?.content?.trim() || VERSION;
}
